version: "3.9"

services:
  moderator-bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATA_DIR=/app/data
    volumes:
      - bot_data:/app/data

volumes:
  bot_data:
